export const routes = {
    LOGIN: 'LoginScreen',
    DASHBOARD: 'DashBoardScreen',
    FORGOT: 'ForgotPasswordScreen',
    VERIFY: 'VerifyOTPScreen',
    ACCOUNT: 'AccountScreen',
    HISTORY:'HistoryScreen',
    POSITION: 'PositionScreen',
    AMOUNT: 'ChooseAmountScreen',
    LOCATION: 'LocationScreen',
    CURRENTLOCATION: 'CurrentLocationScreen',
    COMPANY: 'CompanyScreen',
    CHECKOUT: 'CheckOutScreen',
    ORDER: 'OrderScreen',
    SPLASH: 'SplashScreen',
    REGISTER: 'RegisterScreen',
    HOMETAB: 'HomeTabScreen',
    HOMETABCOMPANY: 'HomeTabCompanyScreen',
    HOMEDRAWER: 'HomeDrawerScreen',
    PROFILETAB: 'ProfieTabScreen',
    FAVORITES: 'FavoritesTabScreen',
    BASKETTAB: 'BasketTabScreen',
    RESTAURANT: 'RestaurantTabScreen',
    HOME: 'HomeStackScreen',
    HOMECOMPANY: 'HomeCompanyStackScreen',
    DETAIL: 'DetailStackScreen',
    BASKET: 'BasketStackScreen',
    DELIVERY: 'DeliveyStackScreen',
    PROFILE: 'ProfileStackScreen',
    RESTAURANTDETAIL: 'RestaurantDetailStackScreen',
  };